#+STARTUP: showall
* Bugs and limitations in Xray::BLA and Metis

** Issues with Xray::BLA [4/16]

 - [ ] More robust error handling.

 - [X] When a mask processing step results in 0 illuminated pixels,
   Metis crashes.  Should reset working_image to prior state if 0
   pixels illuminated.

 - [ ] More testing.

 - [ ] Use the energy map to create a mask with a specified energy width.

 - [X] In the future, will need a more sophisticated mechanism for
   relating C<stub> to scan file and to image files -- some kind of
   templating scheme, I suspect

 - [ ] Parse columns of scan file and patern match to find the useful
   columns.  Too much assumption goes into the scan method.  Also will
   need a flag to say whether conventional data was gathered from the
   scan file.  Also need a way to choose between transmission and
   conventional fluorescence, which may be done with an SDD.

 - [X] Drop current crop of gnuplot+Text::Template methods in favor of
   PDL::Graphics::Gnuplot.  ~or not -- it's handy to write out the .gp file.~

 - [ ] gnuplot file for rixs map -- how is this done in PDL?  PDL has
   linear axis transforms, but can it do non-linear transforms
   specified point-by-point?

 - [ ] Other energy map output formats.  A gif would be useful.  (Much
   easier using PDL)

 - [ ] consider using MooseX::GetSet

 - [ ] It should not be necessary to specify the list of elastic
   energies in the config file.  They could be culled from the file
   names or from a file of metadata.  (As in Metis)

 - [X] Figure out element and emission line by comparing the midpoint
   of the range of elastic energies to a table of line energies.

 - [ ] Use of XDI is undocumented.  And incomplete.  And, frankly,
   Xray::XDI needs attention.

 - [ ] Think about how to use HDF5 to store images, scans, scan
   metadata, and Xray::BLA metadata.

 - [ ] Configurable data columns -- need to be more flexible about
   content of scan file.  Also need to be able to configure column
   with conventional XAFS for mu(E) plot.  See Xray/BLA.pm line 568,
   loop over energy points in ~scan~ method.

 - [ ] Maybe use object oriented plotting interface ....

** Issues with Metis [9/17]

 - [X] Version 2 will have Xray::BLA objects for each emission energy
   and one for the aggregate object.  That will make XES and RIXS much
   simpler to implement sensibly.  Will also allow me to dump the
   working_image concept.

 - [X] implement XES and RIXS

 - [X] replot RIXS & export Athena project file from RIXS

 - [X] flag whether steps have changed, don't recompute masks for XES
   at a different incident energy

 - [X] Resetting a mask leads to crashy trouble -- need to investigate

 - [ ] implement map and mapmask

 - [X] implement aggregate mask from set of elastic images

 - [ ] separate stubs for elastic and data images (partially addressed
   by file name templates)

 - [X] widgets for selecting folders.  Wx::FileDialog was causing
   crashes on my home computer.

 - [X] More error checking, edge cases.  For example, what happens
   when a stub + folders does not return a sensible pile of stuff?

 - [ ] mask development animations.  according to the PERLDL mailing
   list, giving file.gif to wmpeg will cause it to write an animated
   gif, assuming ffmpeg is installed on the computer.  this needs
   testing outside of metis.

 - [ ] animation of mask vs. elastic energy

 - [X] some kind of system for specifying file naming patterns -- this
   is somewhat less important now that the contents of the elastic and
   image lists on the Files tool are used explicitly.  if this is
   still ambiguous, a file selection dialog can be used to select
   content for the lists.

 - [ ] Persistance. Need to save group of masks.  Need to save
   aggregate mask.  Need to reimport them.

 - [ ] how are element and line used?  (answer: they are used to set
   the white color band in a map)

 - [ ] Click on image list, show incident energy of that image in the
   status bar

 - [ ] Save metadata from .ini file to RIXS prj file

** Mask algorithm possibilities

 - proper edge detection
 - Fourier filtering

** Rough milestones

 - [X] *Version 2* : XES and RIXS working in Metis
 - [ ] *Version 3* : Whatever is required of Feb 2016 beamtime
 - [ ] *Version 4* : proper test suite, test for and handle edge cases (what did I mean by this?)
 - [ ] *Version 5* : map and mapmask working in Metis
 - [ ] *Version 6* : persistance in Metis, save and recover to current position
