#!/bin/bash


do_sed()
{
    sed -i 's/http:\/\/search.cpan.org\/search/https:\/\/metacpan.org\//g'     $1
    sed -i 's/\?query=/pod\//g'                                                $1
    sed -i 's/&mode=module//g'                                                 $1
    sed -i 's/perlgpl/\`perlgpl <http:\/\/perldoc.perl.org\/perlgpl.html>\`_/' $1
}

pod2rst --infile=../lib/Xray/BLA.pm --outfile lib/Xray/BLA.rst
do_sed lib/Xray/BLA.rst

XB='IO Image Mask Pause Plot Return Tools SplotPalette'
for f in $XB; do
    pod2rst --infile=../lib/Xray/BLA/$f.pm --outfile lib/Xray/BLA/$f.rst
    do_sed lib/Xray/BLA/$f.rst
done

pod2rst --infile=../lib/Demeter/UI/Metis.pm --outfile lib/Demeter/UI/Metis.rst
do_sed lib/Demeter/UI/Metis.rst

DUM='Config Data Files Mask Cursor PluckPoint LastPlot'
for f in $DUM; do
    pod2rst --infile=../lib/Demeter/UI/Metis/$f.pm --outfile lib/Demeter/UI/Metis/$f.rst
    do_sed lib/Demeter/UI/Metis/$f.rst
done
